spring:
  application:
    name: messaging-stomp-websocket-complete

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          naver:
            client-id: <client-id>
            client-secret: <client-secret>
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email
              - username
              - phone

          kakao:
            client-id: <client-id>
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - phone_number
              - name
              - profile_nickname

  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: classpath:/static,file:profile/,file:posting-media/

  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size: 30
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

#  datasource:
#    url: jdbc:mysql://localhost:3306/travel
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: luna
#    password: Mlkfpt@2001
#
#  jpa:
#    hibernate:
#      ddl-auto: create # or validate, create-drop, none as needed
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    generate-ddl: true
#    defer-datasource-initialization: true

jwt:
  secret: <secret>

logging:
  level:
    org:
      springframework:
        web: INFO

server:
  address: 0.0.0.0
  port: 8080

naver:
  client-id: <client-id>
  secret: <secret>

naver-cloud:
  client-id: <client-id>
  secret: <secret>

tour-api:
  serviceKey: <key>

odsay:
  apiKey: <key>

payment:
  toss:
    test_client_api_key: <key>
    test_secret_api_key: <key>
    success_url: http://127.0.0.1:8080/api/v1/payments/toss/success
    fail_url: http://127.0.0.1:8080/api/v1/payments/toss/fail
